// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Configure_STAMP_Status.proto
// Protobuf C++ Version: 6.33.1

#include "Configure_STAMP_Status.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GUIApp {
namespace Comm {

inline constexpr Configure_STAMP_Status::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{static_cast< ::GUIApp::Comm::SystemStatus >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Configure_STAMP_Status::Configure_STAMP_Status(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Configure_STAMP_Status_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Configure_STAMP_StatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Configure_STAMP_StatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Configure_STAMP_StatusDefaultTypeInternal() {}
  union {
    Configure_STAMP_Status _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Configure_STAMP_StatusDefaultTypeInternal _Configure_STAMP_Status_default_instance_;
}  // namespace Comm
}  // namespace GUIApp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_Configure_5fSTAMP_5fStatus_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_Configure_5fSTAMP_5fStatus_2eproto = nullptr;
const ::uint32_t
    TableStruct_Configure_5fSTAMP_5fStatus_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::Configure_STAMP_Status, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::Configure_STAMP_Status, _impl_.status_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::GUIApp::Comm::Configure_STAMP_Status)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::GUIApp::Comm::_Configure_STAMP_Status_default_instance_._instance,
};
const char descriptor_table_protodef_Configure_5fSTAMP_5fStatus_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034Configure_STAMP_Status.proto\022\013GUIApp.C"
    "omm\"C\n\026Configure_STAMP_Status\022)\n\006status\030"
    "\001 \001(\0162\031.GUIApp.Comm.SystemStatus*e\n\014Syst"
    "emStatus\022\027\n\023Status_Initializing\020\000\022\021\n\rSta"
    "tus_Normal\020\001\022\023\n\017Status_Degraded\020\002\022\024\n\020Sta"
    "tus_Inoprable\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_Configure_5fSTAMP_5fStatus_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Configure_5fSTAMP_5fStatus_2eproto = {
    false,
    false,
    223,
    descriptor_table_protodef_Configure_5fSTAMP_5fStatus_2eproto,
    "Configure_STAMP_Status.proto",
    &descriptor_table_Configure_5fSTAMP_5fStatus_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Configure_5fSTAMP_5fStatus_2eproto::offsets,
    file_level_enum_descriptors_Configure_5fSTAMP_5fStatus_2eproto,
    file_level_service_descriptors_Configure_5fSTAMP_5fStatus_2eproto,
};
namespace GUIApp {
namespace Comm {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SystemStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Configure_5fSTAMP_5fStatus_2eproto);
  return file_level_enum_descriptors_Configure_5fSTAMP_5fStatus_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SystemStatus_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class Configure_STAMP_Status::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Configure_STAMP_Status>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Configure_STAMP_Status, _impl_._has_bits_);
};

Configure_STAMP_Status::Configure_STAMP_Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Configure_STAMP_Status_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GUIApp.Comm.Configure_STAMP_Status)
}
Configure_STAMP_Status::Configure_STAMP_Status(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Configure_STAMP_Status& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Configure_STAMP_Status_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Configure_STAMP_Status::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Configure_STAMP_Status::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
Configure_STAMP_Status::~Configure_STAMP_Status() {
  // @@protoc_insertion_point(destructor:GUIApp.Comm.Configure_STAMP_Status)
  SharedDtor(*this);
}
inline void Configure_STAMP_Status::SharedDtor(MessageLite& self) {
  Configure_STAMP_Status& this_ = static_cast<Configure_STAMP_Status&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Configure_STAMP_Status::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Configure_STAMP_Status(arena);
}
constexpr auto Configure_STAMP_Status::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Configure_STAMP_Status),
                                            alignof(Configure_STAMP_Status));
}
constexpr auto Configure_STAMP_Status::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Configure_STAMP_Status_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Configure_STAMP_Status::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Configure_STAMP_Status>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Configure_STAMP_Status::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Configure_STAMP_Status>(), &Configure_STAMP_Status::ByteSizeLong,
              &Configure_STAMP_Status::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Configure_STAMP_Status, _impl_._cached_size_),
          false,
      },
      &Configure_STAMP_Status::kDescriptorMethods,
      &descriptor_table_Configure_5fSTAMP_5fStatus_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Configure_STAMP_Status_class_data_ =
        Configure_STAMP_Status::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Configure_STAMP_Status::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Configure_STAMP_Status_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Configure_STAMP_Status_class_data_.tc_table);
  return Configure_STAMP_Status_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Configure_STAMP_Status::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Configure_STAMP_Status, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Configure_STAMP_Status_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GUIApp::Comm::Configure_STAMP_Status>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .GUIApp.Comm.SystemStatus status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Configure_STAMP_Status, _impl_.status_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(Configure_STAMP_Status, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GUIApp.Comm.SystemStatus status = 1;
    {PROTOBUF_FIELD_OFFSET(Configure_STAMP_Status, _impl_.status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Configure_STAMP_Status::Clear() {
// @@protoc_insertion_point(message_clear_start:GUIApp.Comm.Configure_STAMP_Status)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Configure_STAMP_Status::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Configure_STAMP_Status& this_ = static_cast<const Configure_STAMP_Status&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Configure_STAMP_Status::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Configure_STAMP_Status& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GUIApp.Comm.Configure_STAMP_Status)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .GUIApp.Comm.SystemStatus status = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GUIApp.Comm.Configure_STAMP_Status)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Configure_STAMP_Status::ByteSizeLong(const MessageLite& base) {
  const Configure_STAMP_Status& this_ = static_cast<const Configure_STAMP_Status&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Configure_STAMP_Status::ByteSizeLong() const {
  const Configure_STAMP_Status& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GUIApp.Comm.Configure_STAMP_Status)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .GUIApp.Comm.SystemStatus status = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Configure_STAMP_Status::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Configure_STAMP_Status*>(&to_msg);
  auto& from = static_cast<const Configure_STAMP_Status&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GUIApp.Comm.Configure_STAMP_Status)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_status() != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Configure_STAMP_Status::CopyFrom(const Configure_STAMP_Status& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GUIApp.Comm.Configure_STAMP_Status)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Configure_STAMP_Status::InternalSwap(Configure_STAMP_Status* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata Configure_STAMP_Status::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Configure_5fSTAMP_5fStatus_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
