// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ConfigureBitResults.proto
// Protobuf C++ Version: 6.33.1

#ifndef ConfigureBitResults_2eproto_2epb_2eh
#define ConfigureBitResults_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ConfigureBitResults_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ConfigureBitResults_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ConfigureBitResults_2eproto;
}  // extern "C"
namespace GUIApp {
namespace Comm {
enum BIT_ResponseType : int;
extern const uint32_t BIT_ResponseType_internal_data_[];
class ConfigureBitResults;
struct ConfigureBitResultsDefaultTypeInternal;
extern ConfigureBitResultsDefaultTypeInternal _ConfigureBitResults_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ConfigureBitResults_class_data_;
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::GUIApp::Comm::BIT_ResponseType_internal_data_>
    internal::EnumTraitsImpl::value<::GUIApp::Comm::BIT_ResponseType>;
}  // namespace protobuf
}  // namespace google

namespace GUIApp {
namespace Comm {
enum BIT_ResponseType : int {
  BIT_RESPONSE_PASS = 0,
  BIT_RESPONSE_FAIL = 1,
  BIT_ResponseType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  BIT_ResponseType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t BIT_ResponseType_internal_data_[];
inline constexpr BIT_ResponseType BIT_ResponseType_MIN =
    static_cast<BIT_ResponseType>(0);
inline constexpr BIT_ResponseType BIT_ResponseType_MAX =
    static_cast<BIT_ResponseType>(1);
inline bool BIT_ResponseType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int BIT_ResponseType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL BIT_ResponseType_descriptor();
template <typename T>
const ::std::string& BIT_ResponseType_Name(T value) {
  static_assert(::std::is_same<T, BIT_ResponseType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to BIT_ResponseType_Name().");
  return BIT_ResponseType_Name(static_cast<BIT_ResponseType>(value));
}
template <>
inline const ::std::string& BIT_ResponseType_Name(BIT_ResponseType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<BIT_ResponseType_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool BIT_ResponseType_Parse(
    ::absl::string_view name, BIT_ResponseType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<BIT_ResponseType>(BIT_ResponseType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class ConfigureBitResults final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GUIApp.Comm.ConfigureBitResults) */ {
 public:
  inline ConfigureBitResults() : ConfigureBitResults(nullptr) {}
  ~ConfigureBitResults() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConfigureBitResults* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConfigureBitResults));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConfigureBitResults(::google::protobuf::internal::ConstantInitialized);

  inline ConfigureBitResults(const ConfigureBitResults& from) : ConfigureBitResults(nullptr, from) {}
  inline ConfigureBitResults(ConfigureBitResults&& from) noexcept
      : ConfigureBitResults(nullptr, ::std::move(from)) {}
  inline ConfigureBitResults& operator=(const ConfigureBitResults& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigureBitResults& operator=(ConfigureBitResults&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigureBitResults& default_instance() {
    return *reinterpret_cast<const ConfigureBitResults*>(
        &_ConfigureBitResults_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ConfigureBitResults& a, ConfigureBitResults& b) { a.Swap(&b); }
  inline void Swap(ConfigureBitResults* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigureBitResults* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigureBitResults* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConfigureBitResults>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConfigureBitResults& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConfigureBitResults& from) { ConfigureBitResults::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConfigureBitResults* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GUIApp.Comm.ConfigureBitResults"; }

  explicit ConfigureBitResults(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ConfigureBitResults(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConfigureBitResults& from);
  ConfigureBitResults(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ConfigureBitResults&& from) noexcept
      : ConfigureBitResults(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBitResponseFieldNumber = 1,
    kDurationIfSetToFailMsecFieldNumber = 2,
  };
  // .GUIApp.Comm.BIT_ResponseType BitResponse = 1;
  void clear_bitresponse() ;
  ::GUIApp::Comm::BIT_ResponseType bitresponse() const;
  void set_bitresponse(::GUIApp::Comm::BIT_ResponseType value);

  private:
  ::GUIApp::Comm::BIT_ResponseType _internal_bitresponse() const;
  void _internal_set_bitresponse(::GUIApp::Comm::BIT_ResponseType value);

  public:
  // int32 DurationIfSetToFail_msec = 2;
  void clear_durationifsettofail_msec() ;
  ::int32_t durationifsettofail_msec() const;
  void set_durationifsettofail_msec(::int32_t value);

  private:
  ::int32_t _internal_durationifsettofail_msec() const;
  void _internal_set_durationifsettofail_msec(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GUIApp.Comm.ConfigureBitResults)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ConfigureBitResults& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int bitresponse_;
    ::int32_t durationifsettofail_msec_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ConfigureBitResults_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ConfigureBitResults_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ConfigureBitResults

// .GUIApp.Comm.BIT_ResponseType BitResponse = 1;
inline void ConfigureBitResults::clear_bitresponse() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bitresponse_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::GUIApp::Comm::BIT_ResponseType ConfigureBitResults::bitresponse() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.ConfigureBitResults.BitResponse)
  return _internal_bitresponse();
}
inline void ConfigureBitResults::set_bitresponse(::GUIApp::Comm::BIT_ResponseType value) {
  _internal_set_bitresponse(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.ConfigureBitResults.BitResponse)
}
inline ::GUIApp::Comm::BIT_ResponseType ConfigureBitResults::_internal_bitresponse() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GUIApp::Comm::BIT_ResponseType>(_impl_.bitresponse_);
}
inline void ConfigureBitResults::_internal_set_bitresponse(::GUIApp::Comm::BIT_ResponseType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bitresponse_ = value;
}

// int32 DurationIfSetToFail_msec = 2;
inline void ConfigureBitResults::clear_durationifsettofail_msec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.durationifsettofail_msec_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t ConfigureBitResults::durationifsettofail_msec() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.ConfigureBitResults.DurationIfSetToFail_msec)
  return _internal_durationifsettofail_msec();
}
inline void ConfigureBitResults::set_durationifsettofail_msec(::int32_t value) {
  _internal_set_durationifsettofail_msec(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.ConfigureBitResults.DurationIfSetToFail_msec)
}
inline ::int32_t ConfigureBitResults::_internal_durationifsettofail_msec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.durationifsettofail_msec_;
}
inline void ConfigureBitResults::_internal_set_durationifsettofail_msec(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.durationifsettofail_msec_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GUIApp::Comm::BIT_ResponseType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GUIApp::Comm::BIT_ResponseType>() {
  return ::GUIApp::Comm::BIT_ResponseType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ConfigureBitResults_2eproto_2epb_2eh
