// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Configure_STAMP_Status.proto
// Protobuf C++ Version: 6.33.1

#ifndef Configure_5fSTAMP_5fStatus_2eproto_2epb_2eh
#define Configure_5fSTAMP_5fStatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Configure_5fSTAMP_5fStatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Configure_5fSTAMP_5fStatus_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Configure_5fSTAMP_5fStatus_2eproto;
}  // extern "C"
namespace GUIApp {
namespace Comm {
enum SystemStatus : int;
extern const uint32_t SystemStatus_internal_data_[];
class Configure_STAMP_Status;
struct Configure_STAMP_StatusDefaultTypeInternal;
extern Configure_STAMP_StatusDefaultTypeInternal _Configure_STAMP_Status_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Configure_STAMP_Status_class_data_;
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::GUIApp::Comm::SystemStatus_internal_data_>
    internal::EnumTraitsImpl::value<::GUIApp::Comm::SystemStatus>;
}  // namespace protobuf
}  // namespace google

namespace GUIApp {
namespace Comm {
enum SystemStatus : int {
  Status_Initializing = 0,
  Status_Normal = 1,
  Status_Degraded = 2,
  Status_Inoprable = 3,
  SystemStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  SystemStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t SystemStatus_internal_data_[];
inline constexpr SystemStatus SystemStatus_MIN =
    static_cast<SystemStatus>(0);
inline constexpr SystemStatus SystemStatus_MAX =
    static_cast<SystemStatus>(3);
inline bool SystemStatus_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int SystemStatus_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SystemStatus_descriptor();
template <typename T>
const ::std::string& SystemStatus_Name(T value) {
  static_assert(::std::is_same<T, SystemStatus>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to SystemStatus_Name().");
  return SystemStatus_Name(static_cast<SystemStatus>(value));
}
template <>
inline const ::std::string& SystemStatus_Name(SystemStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SystemStatus_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool SystemStatus_Parse(
    ::absl::string_view name, SystemStatus* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<SystemStatus>(SystemStatus_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Configure_STAMP_Status final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GUIApp.Comm.Configure_STAMP_Status) */ {
 public:
  inline Configure_STAMP_Status() : Configure_STAMP_Status(nullptr) {}
  ~Configure_STAMP_Status() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Configure_STAMP_Status* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Configure_STAMP_Status));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Configure_STAMP_Status(::google::protobuf::internal::ConstantInitialized);

  inline Configure_STAMP_Status(const Configure_STAMP_Status& from) : Configure_STAMP_Status(nullptr, from) {}
  inline Configure_STAMP_Status(Configure_STAMP_Status&& from) noexcept
      : Configure_STAMP_Status(nullptr, ::std::move(from)) {}
  inline Configure_STAMP_Status& operator=(const Configure_STAMP_Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Configure_STAMP_Status& operator=(Configure_STAMP_Status&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Configure_STAMP_Status& default_instance() {
    return *reinterpret_cast<const Configure_STAMP_Status*>(
        &_Configure_STAMP_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Configure_STAMP_Status& a, Configure_STAMP_Status& b) { a.Swap(&b); }
  inline void Swap(Configure_STAMP_Status* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Configure_STAMP_Status* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Configure_STAMP_Status* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Configure_STAMP_Status>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Configure_STAMP_Status& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Configure_STAMP_Status& from) { Configure_STAMP_Status::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Configure_STAMP_Status* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GUIApp.Comm.Configure_STAMP_Status"; }

  explicit Configure_STAMP_Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Configure_STAMP_Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Configure_STAMP_Status& from);
  Configure_STAMP_Status(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Configure_STAMP_Status&& from) noexcept
      : Configure_STAMP_Status(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // .GUIApp.Comm.SystemStatus status = 1;
  void clear_status() ;
  ::GUIApp::Comm::SystemStatus status() const;
  void set_status(::GUIApp::Comm::SystemStatus value);

  private:
  ::GUIApp::Comm::SystemStatus _internal_status() const;
  void _internal_set_status(::GUIApp::Comm::SystemStatus value);

  public:
  // @@protoc_insertion_point(class_scope:GUIApp.Comm.Configure_STAMP_Status)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Configure_STAMP_Status& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Configure_5fSTAMP_5fStatus_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Configure_STAMP_Status_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Configure_STAMP_Status

// .GUIApp.Comm.SystemStatus status = 1;
inline void Configure_STAMP_Status::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::GUIApp::Comm::SystemStatus Configure_STAMP_Status::status() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.Configure_STAMP_Status.status)
  return _internal_status();
}
inline void Configure_STAMP_Status::set_status(::GUIApp::Comm::SystemStatus value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.Configure_STAMP_Status.status)
}
inline ::GUIApp::Comm::SystemStatus Configure_STAMP_Status::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GUIApp::Comm::SystemStatus>(_impl_.status_);
}
inline void Configure_STAMP_Status::_internal_set_status(::GUIApp::Comm::SystemStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GUIApp::Comm::SystemStatus> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GUIApp::Comm::SystemStatus>() {
  return ::GUIApp::Comm::SystemStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Configure_5fSTAMP_5fStatus_2eproto_2epb_2eh
