// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ConfigureBitResults.proto
// Protobuf C++ Version: 6.33.1

#include "ConfigureBitResults.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GUIApp {
namespace Comm {

inline constexpr ConfigureBitResults::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bitresponse_{static_cast< ::GUIApp::Comm::BIT_ResponseType >(0)},
        durationifsettofail_msec_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConfigureBitResults::ConfigureBitResults(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ConfigureBitResults_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConfigureBitResultsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigureBitResultsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigureBitResultsDefaultTypeInternal() {}
  union {
    ConfigureBitResults _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigureBitResultsDefaultTypeInternal _ConfigureBitResults_default_instance_;
}  // namespace Comm
}  // namespace GUIApp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_ConfigureBitResults_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_ConfigureBitResults_2eproto = nullptr;
const ::uint32_t
    TableStruct_ConfigureBitResults_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::ConfigureBitResults, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::ConfigureBitResults, _impl_.bitresponse_),
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::ConfigureBitResults, _impl_.durationifsettofail_msec_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::GUIApp::Comm::ConfigureBitResults)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::GUIApp::Comm::_ConfigureBitResults_default_instance_._instance,
};
const char descriptor_table_protodef_ConfigureBitResults_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031ConfigureBitResults.proto\022\013GUIApp.Comm"
    "\"k\n\023ConfigureBitResults\0222\n\013BitResponse\030\001"
    " \001(\0162\035.GUIApp.Comm.BIT_ResponseType\022 \n\030D"
    "urationIfSetToFail_msec\030\002 \001(\005*@\n\020BIT_Res"
    "ponseType\022\025\n\021BIT_RESPONSE_PASS\020\000\022\025\n\021BIT_"
    "RESPONSE_FAIL\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_ConfigureBitResults_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ConfigureBitResults_2eproto = {
    false,
    false,
    223,
    descriptor_table_protodef_ConfigureBitResults_2eproto,
    "ConfigureBitResults.proto",
    &descriptor_table_ConfigureBitResults_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ConfigureBitResults_2eproto::offsets,
    file_level_enum_descriptors_ConfigureBitResults_2eproto,
    file_level_service_descriptors_ConfigureBitResults_2eproto,
};
namespace GUIApp {
namespace Comm {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL BIT_ResponseType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ConfigureBitResults_2eproto);
  return file_level_enum_descriptors_ConfigureBitResults_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t BIT_ResponseType_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class ConfigureBitResults::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ConfigureBitResults>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_._has_bits_);
};

ConfigureBitResults::ConfigureBitResults(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigureBitResults_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GUIApp.Comm.ConfigureBitResults)
}
ConfigureBitResults::ConfigureBitResults(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConfigureBitResults& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigureBitResults_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ConfigureBitResults::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ConfigureBitResults::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, bitresponse_),
           0,
           offsetof(Impl_, durationifsettofail_msec_) -
               offsetof(Impl_, bitresponse_) +
               sizeof(Impl_::durationifsettofail_msec_));
}
ConfigureBitResults::~ConfigureBitResults() {
  // @@protoc_insertion_point(destructor:GUIApp.Comm.ConfigureBitResults)
  SharedDtor(*this);
}
inline void ConfigureBitResults::SharedDtor(MessageLite& self) {
  ConfigureBitResults& this_ = static_cast<ConfigureBitResults&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ConfigureBitResults::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ConfigureBitResults(arena);
}
constexpr auto ConfigureBitResults::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ConfigureBitResults),
                                            alignof(ConfigureBitResults));
}
constexpr auto ConfigureBitResults::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ConfigureBitResults_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ConfigureBitResults::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ConfigureBitResults>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ConfigureBitResults::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ConfigureBitResults>(), &ConfigureBitResults::ByteSizeLong,
              &ConfigureBitResults::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_._cached_size_),
          false,
      },
      &ConfigureBitResults::kDescriptorMethods,
      &descriptor_table_ConfigureBitResults_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ConfigureBitResults_class_data_ =
        ConfigureBitResults::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ConfigureBitResults::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ConfigureBitResults_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ConfigureBitResults_class_data_.tc_table);
  return ConfigureBitResults_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
ConfigureBitResults::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ConfigureBitResults_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GUIApp::Comm::ConfigureBitResults>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 DurationIfSetToFail_msec = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConfigureBitResults, _impl_.durationifsettofail_msec_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_.durationifsettofail_msec_)}},
    // .GUIApp.Comm.BIT_ResponseType BitResponse = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConfigureBitResults, _impl_.bitresponse_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_.bitresponse_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GUIApp.Comm.BIT_ResponseType BitResponse = 1;
    {PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_.bitresponse_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int32 DurationIfSetToFail_msec = 2;
    {PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_.durationifsettofail_msec_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ConfigureBitResults::Clear() {
// @@protoc_insertion_point(message_clear_start:GUIApp.Comm.ConfigureBitResults)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.bitresponse_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.durationifsettofail_msec_) -
        reinterpret_cast<char*>(&_impl_.bitresponse_)) + sizeof(_impl_.durationifsettofail_msec_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ConfigureBitResults::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ConfigureBitResults& this_ = static_cast<const ConfigureBitResults&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ConfigureBitResults::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ConfigureBitResults& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GUIApp.Comm.ConfigureBitResults)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .GUIApp.Comm.BIT_ResponseType BitResponse = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_bitresponse() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_bitresponse(), target);
    }
  }

  // int32 DurationIfSetToFail_msec = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_durationifsettofail_msec() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_durationifsettofail_msec(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GUIApp.Comm.ConfigureBitResults)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ConfigureBitResults::ByteSizeLong(const MessageLite& base) {
  const ConfigureBitResults& this_ = static_cast<const ConfigureBitResults&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ConfigureBitResults::ByteSizeLong() const {
  const ConfigureBitResults& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GUIApp.Comm.ConfigureBitResults)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .GUIApp.Comm.BIT_ResponseType BitResponse = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_bitresponse() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_bitresponse());
      }
    }
    // int32 DurationIfSetToFail_msec = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_durationifsettofail_msec() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_durationifsettofail_msec());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ConfigureBitResults::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ConfigureBitResults*>(&to_msg);
  auto& from = static_cast<const ConfigureBitResults&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GUIApp.Comm.ConfigureBitResults)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_bitresponse() != 0) {
        _this->_impl_.bitresponse_ = from._impl_.bitresponse_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_durationifsettofail_msec() != 0) {
        _this->_impl_.durationifsettofail_msec_ = from._impl_.durationifsettofail_msec_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ConfigureBitResults::CopyFrom(const ConfigureBitResults& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GUIApp.Comm.ConfigureBitResults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ConfigureBitResults::InternalSwap(ConfigureBitResults* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_.durationifsettofail_msec_)
      + sizeof(ConfigureBitResults::_impl_.durationifsettofail_msec_)
      - PROTOBUF_FIELD_OFFSET(ConfigureBitResults, _impl_.bitresponse_)>(
          reinterpret_cast<char*>(&_impl_.bitresponse_),
          reinterpret_cast<char*>(&other->_impl_.bitresponse_));
}

::google::protobuf::Metadata ConfigureBitResults::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ConfigureBitResults_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
