// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SimulatorStatus.proto
// Protobuf C++ Version: 6.33.1

#include "SimulatorStatus.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GUIApp {
namespace Comm {

inline constexpr SubsystemStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{static_cast< ::GUIApp::Comm::SystemStatus >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR SubsystemStatus::SubsystemStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SubsystemStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SubsystemStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubsystemStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubsystemStatusDefaultTypeInternal() {}
  union {
    SubsystemStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubsystemStatusDefaultTypeInternal _SubsystemStatus_default_instance_;

inline constexpr SimulatorStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ipaddress_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uptimeseconds_{0},
        port_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SimulatorStatus::SimulatorStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SimulatorStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SimulatorStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimulatorStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimulatorStatusDefaultTypeInternal() {}
  union {
    SimulatorStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimulatorStatusDefaultTypeInternal _SimulatorStatus_default_instance_;
}  // namespace Comm
}  // namespace GUIApp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_SimulatorStatus_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_SimulatorStatus_2eproto = nullptr;
const ::uint32_t
    TableStruct_SimulatorStatus_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::SimulatorStatus, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::SimulatorStatus, _impl_.uptimeseconds_),
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::SimulatorStatus, _impl_.ipaddress_),
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::SimulatorStatus, _impl_.port_),
        1,
        0,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::SubsystemStatus, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::SubsystemStatus, _impl_.status_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::GUIApp::Comm::SimulatorStatus)},
        {9, sizeof(::GUIApp::Comm::SubsystemStatus)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::GUIApp::Comm::_SimulatorStatus_default_instance_._instance,
    &::GUIApp::Comm::_SubsystemStatus_default_instance_._instance,
};
const char descriptor_table_protodef_SimulatorStatus_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025SimulatorStatus.proto\022\013GUIApp.Comm\"I\n\017"
    "SimulatorStatus\022\025\n\ruptimeSeconds\030\001 \001(\005\022\021"
    "\n\tipAddress\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"<\n\017Subsy"
    "stemStatus\022)\n\006status\030\001 \001(\0162\031.GUIApp.Comm"
    ".SystemStatus*1\n\014SystemStatus\022\020\n\014Initial"
    "izing\020\000\022\017\n\013Operational\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_SimulatorStatus_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SimulatorStatus_2eproto = {
    false,
    false,
    232,
    descriptor_table_protodef_SimulatorStatus_2eproto,
    "SimulatorStatus.proto",
    &descriptor_table_SimulatorStatus_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_SimulatorStatus_2eproto::offsets,
    file_level_enum_descriptors_SimulatorStatus_2eproto,
    file_level_service_descriptors_SimulatorStatus_2eproto,
};
namespace GUIApp {
namespace Comm {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SystemStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_SimulatorStatus_2eproto);
  return file_level_enum_descriptors_SimulatorStatus_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SystemStatus_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class SimulatorStatus::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SimulatorStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_._has_bits_);
};

SimulatorStatus::SimulatorStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SimulatorStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GUIApp.Comm.SimulatorStatus)
}
PROTOBUF_NDEBUG_INLINE SimulatorStatus::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::GUIApp::Comm::SimulatorStatus& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ipaddress_(arena, from.ipaddress_) {}

SimulatorStatus::SimulatorStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SimulatorStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SimulatorStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SimulatorStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, uptimeseconds_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, uptimeseconds_),
           offsetof(Impl_, port_) -
               offsetof(Impl_, uptimeseconds_) +
               sizeof(Impl_::port_));

  // @@protoc_insertion_point(copy_constructor:GUIApp.Comm.SimulatorStatus)
}
PROTOBUF_NDEBUG_INLINE SimulatorStatus::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ipaddress_(arena) {}

inline void SimulatorStatus::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, uptimeseconds_),
           0,
           offsetof(Impl_, port_) -
               offsetof(Impl_, uptimeseconds_) +
               sizeof(Impl_::port_));
}
SimulatorStatus::~SimulatorStatus() {
  // @@protoc_insertion_point(destructor:GUIApp.Comm.SimulatorStatus)
  SharedDtor(*this);
}
inline void SimulatorStatus::SharedDtor(MessageLite& self) {
  SimulatorStatus& this_ = static_cast<SimulatorStatus&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ipaddress_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SimulatorStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SimulatorStatus(arena);
}
constexpr auto SimulatorStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SimulatorStatus),
                                            alignof(SimulatorStatus));
}
constexpr auto SimulatorStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SimulatorStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SimulatorStatus::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SimulatorStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SimulatorStatus::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SimulatorStatus>(), &SimulatorStatus::ByteSizeLong,
              &SimulatorStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_._cached_size_),
          false,
      },
      &SimulatorStatus::kDescriptorMethods,
      &descriptor_table_SimulatorStatus_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SimulatorStatus_class_data_ =
        SimulatorStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SimulatorStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SimulatorStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SimulatorStatus_class_data_.tc_table);
  return SimulatorStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 45, 2>
SimulatorStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SimulatorStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GUIApp::Comm::SimulatorStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 uptimeSeconds = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SimulatorStatus, _impl_.uptimeseconds_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.uptimeseconds_)}},
    // string ipAddress = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.ipaddress_)}},
    // int32 port = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SimulatorStatus, _impl_.port_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 uptimeSeconds = 1;
    {PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.uptimeseconds_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string ipAddress = 2;
    {PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.ipaddress_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 port = 3;
    {PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.port_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\33\0\11\0\0\0\0\0"
    "GUIApp.Comm.SimulatorStatus"
    "ipAddress"
  }},
};
PROTOBUF_NOINLINE void SimulatorStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:GUIApp.Comm.SimulatorStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.ipaddress_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.uptimeseconds_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.port_) -
        reinterpret_cast<char*>(&_impl_.uptimeseconds_)) + sizeof(_impl_.port_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SimulatorStatus::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SimulatorStatus& this_ = static_cast<const SimulatorStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SimulatorStatus::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SimulatorStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GUIApp.Comm.SimulatorStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 uptimeSeconds = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_uptimeseconds() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_uptimeseconds(), target);
    }
  }

  // string ipAddress = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ipaddress().empty()) {
      const ::std::string& _s = this_._internal_ipaddress();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GUIApp.Comm.SimulatorStatus.ipAddress");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 port = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_port() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_port(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GUIApp.Comm.SimulatorStatus)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SimulatorStatus::ByteSizeLong(const MessageLite& base) {
  const SimulatorStatus& this_ = static_cast<const SimulatorStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SimulatorStatus::ByteSizeLong() const {
  const SimulatorStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GUIApp.Comm.SimulatorStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string ipAddress = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ipaddress().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ipaddress());
      }
    }
    // int32 uptimeSeconds = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_uptimeseconds() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_uptimeseconds());
      }
    }
    // int32 port = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_port() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_port());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SimulatorStatus::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SimulatorStatus*>(&to_msg);
  auto& from = static_cast<const SimulatorStatus&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GUIApp.Comm.SimulatorStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_ipaddress().empty()) {
        _this->_internal_set_ipaddress(from._internal_ipaddress());
      } else {
        if (_this->_impl_.ipaddress_.IsDefault()) {
          _this->_internal_set_ipaddress("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_uptimeseconds() != 0) {
        _this->_impl_.uptimeseconds_ = from._impl_.uptimeseconds_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_port() != 0) {
        _this->_impl_.port_ = from._impl_.port_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SimulatorStatus::CopyFrom(const SimulatorStatus& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GUIApp.Comm.SimulatorStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SimulatorStatus::InternalSwap(SimulatorStatus* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ipaddress_, &other->_impl_.ipaddress_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.port_)
      + sizeof(SimulatorStatus::_impl_.port_)
      - PROTOBUF_FIELD_OFFSET(SimulatorStatus, _impl_.uptimeseconds_)>(
          reinterpret_cast<char*>(&_impl_.uptimeseconds_),
          reinterpret_cast<char*>(&other->_impl_.uptimeseconds_));
}

::google::protobuf::Metadata SimulatorStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SubsystemStatus::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SubsystemStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SubsystemStatus, _impl_._has_bits_);
};

SubsystemStatus::SubsystemStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SubsystemStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GUIApp.Comm.SubsystemStatus)
}
SubsystemStatus::SubsystemStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SubsystemStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SubsystemStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SubsystemStatus::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SubsystemStatus::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
SubsystemStatus::~SubsystemStatus() {
  // @@protoc_insertion_point(destructor:GUIApp.Comm.SubsystemStatus)
  SharedDtor(*this);
}
inline void SubsystemStatus::SharedDtor(MessageLite& self) {
  SubsystemStatus& this_ = static_cast<SubsystemStatus&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SubsystemStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SubsystemStatus(arena);
}
constexpr auto SubsystemStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SubsystemStatus),
                                            alignof(SubsystemStatus));
}
constexpr auto SubsystemStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SubsystemStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SubsystemStatus::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SubsystemStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SubsystemStatus::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SubsystemStatus>(), &SubsystemStatus::ByteSizeLong,
              &SubsystemStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SubsystemStatus, _impl_._cached_size_),
          false,
      },
      &SubsystemStatus::kDescriptorMethods,
      &descriptor_table_SimulatorStatus_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SubsystemStatus_class_data_ =
        SubsystemStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SubsystemStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SubsystemStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SubsystemStatus_class_data_.tc_table);
  return SubsystemStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
SubsystemStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SubsystemStatus, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SubsystemStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GUIApp::Comm::SubsystemStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .GUIApp.Comm.SystemStatus status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SubsystemStatus, _impl_.status_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SubsystemStatus, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GUIApp.Comm.SystemStatus status = 1;
    {PROTOBUF_FIELD_OFFSET(SubsystemStatus, _impl_.status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SubsystemStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:GUIApp.Comm.SubsystemStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SubsystemStatus::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SubsystemStatus& this_ = static_cast<const SubsystemStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SubsystemStatus::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SubsystemStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GUIApp.Comm.SubsystemStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .GUIApp.Comm.SystemStatus status = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GUIApp.Comm.SubsystemStatus)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SubsystemStatus::ByteSizeLong(const MessageLite& base) {
  const SubsystemStatus& this_ = static_cast<const SubsystemStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SubsystemStatus::ByteSizeLong() const {
  const SubsystemStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GUIApp.Comm.SubsystemStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .GUIApp.Comm.SystemStatus status = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SubsystemStatus::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SubsystemStatus*>(&to_msg);
  auto& from = static_cast<const SubsystemStatus&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GUIApp.Comm.SubsystemStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_status() != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SubsystemStatus::CopyFrom(const SubsystemStatus& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GUIApp.Comm.SubsystemStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SubsystemStatus::InternalSwap(SubsystemStatus* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata SubsystemStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_SimulatorStatus_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
