// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimulatorStatus.proto

#ifndef PROTOBUF_INCLUDED_SimulatorStatus_2eproto
#define PROTOBUF_INCLUDED_SimulatorStatus_2eproto

#include <string>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>

namespace GUIApp {
namespace Comm {

class SimulatorStatus : public ::google::protobuf::Message {
 public:
  SimulatorStatus();
  virtual ~SimulatorStatus();

  SimulatorStatus(const SimulatorStatus& from);

  inline SimulatorStatus& operator=(const SimulatorStatus& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimulatorStatus& default_instance();

  void Swap(SimulatorStatus* other);

  // implements Message
  SimulatorStatus* New() const final;
  SimulatorStatus* New(::google::protobuf::Arena* arena) const final;
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SimulatorStatus& from);
  void MergeFrom(const SimulatorStatus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;

  // Accessors
  void clear_ipaddress();
  const ::std::string& ipaddress() const;
  void set_ipaddress(const ::std::string& value);
  void set_ipaddress(const char* value);
  void set_ipaddress(const char* value, size_t size);
  ::std::string* mutable_ipaddress();
  ::std::string* release_ipaddress();
  void set_allocated_ipaddress(::std::string* ipaddress);

  void clear_uptimeseconds();
  ::google::protobuf::int32 uptimeseconds() const;
  void set_uptimeseconds(::google::protobuf::int32 value);

  void clear_port();
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

 private:
  ::google::protobuf::internal::ArenaStringPtr ipaddress_;
  ::google::protobuf::int32 uptimeseconds_;
  ::google::protobuf::int32 port_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
};

}  // namespace Comm
}  // namespace GUIApp

#endif  // PROTOBUF_INCLUDED_SimulatorStatus_2eproto
