// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SimulatorStatus.proto
// Protobuf C++ Version: 5.29.5

#ifndef SimulatorStatus_2eproto_2epb_2eh
#define SimulatorStatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SimulatorStatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SimulatorStatus_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SimulatorStatus_2eproto;
namespace GUIApp {
namespace Comm {
class STAMP_Status;
struct STAMP_StatusDefaultTypeInternal;
extern STAMP_StatusDefaultTypeInternal _STAMP_Status_default_instance_;
class SimulatorStatus;
struct SimulatorStatusDefaultTypeInternal;
extern SimulatorStatusDefaultTypeInternal _SimulatorStatus_default_instance_;
class SubsystemStatus;
struct SubsystemStatusDefaultTypeInternal;
extern SubsystemStatusDefaultTypeInternal _SubsystemStatus_default_instance_;
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace GUIApp {
namespace Comm {
enum SystemStatus : int {
  Initializing = 0,
  Operational = 1,
  SystemStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SystemStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SystemStatus_IsValid(int value);
extern const uint32_t SystemStatus_internal_data_[];
constexpr SystemStatus SystemStatus_MIN = static_cast<SystemStatus>(0);
constexpr SystemStatus SystemStatus_MAX = static_cast<SystemStatus>(1);
constexpr int SystemStatus_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
SystemStatus_descriptor();
template <typename T>
const std::string& SystemStatus_Name(T value) {
  static_assert(std::is_same<T, SystemStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SystemStatus_Name().");
  return SystemStatus_Name(static_cast<SystemStatus>(value));
}
template <>
inline const std::string& SystemStatus_Name(SystemStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SystemStatus_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool SystemStatus_Parse(absl::string_view name, SystemStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SystemStatus>(
      SystemStatus_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class SubsystemStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GUIApp.Comm.SubsystemStatus) */ {
 public:
  inline SubsystemStatus() : SubsystemStatus(nullptr) {}
  ~SubsystemStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SubsystemStatus* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SubsystemStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SubsystemStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline SubsystemStatus(const SubsystemStatus& from) : SubsystemStatus(nullptr, from) {}
  inline SubsystemStatus(SubsystemStatus&& from) noexcept
      : SubsystemStatus(nullptr, std::move(from)) {}
  inline SubsystemStatus& operator=(const SubsystemStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubsystemStatus& operator=(SubsystemStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubsystemStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubsystemStatus* internal_default_instance() {
    return reinterpret_cast<const SubsystemStatus*>(
        &_SubsystemStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SubsystemStatus& a, SubsystemStatus& b) { a.Swap(&b); }
  inline void Swap(SubsystemStatus* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubsystemStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubsystemStatus* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SubsystemStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SubsystemStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SubsystemStatus& from) { SubsystemStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SubsystemStatus* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GUIApp.Comm.SubsystemStatus"; }

 protected:
  explicit SubsystemStatus(::google::protobuf::Arena* arena);
  SubsystemStatus(::google::protobuf::Arena* arena, const SubsystemStatus& from);
  SubsystemStatus(::google::protobuf::Arena* arena, SubsystemStatus&& from) noexcept
      : SubsystemStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // .GUIApp.Comm.SystemStatus status = 1;
  void clear_status() ;
  ::GUIApp::Comm::SystemStatus status() const;
  void set_status(::GUIApp::Comm::SystemStatus value);

  private:
  ::GUIApp::Comm::SystemStatus _internal_status() const;
  void _internal_set_status(::GUIApp::Comm::SystemStatus value);

  public:
  // @@protoc_insertion_point(class_scope:GUIApp.Comm.SubsystemStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SubsystemStatus& from_msg);
    int status_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimulatorStatus_2eproto;
};
// -------------------------------------------------------------------

class SimulatorStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GUIApp.Comm.SimulatorStatus) */ {
 public:
  inline SimulatorStatus() : SimulatorStatus(nullptr) {}
  ~SimulatorStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SimulatorStatus* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SimulatorStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SimulatorStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline SimulatorStatus(const SimulatorStatus& from) : SimulatorStatus(nullptr, from) {}
  inline SimulatorStatus(SimulatorStatus&& from) noexcept
      : SimulatorStatus(nullptr, std::move(from)) {}
  inline SimulatorStatus& operator=(const SimulatorStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimulatorStatus& operator=(SimulatorStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SimulatorStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimulatorStatus* internal_default_instance() {
    return reinterpret_cast<const SimulatorStatus*>(
        &_SimulatorStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SimulatorStatus& a, SimulatorStatus& b) { a.Swap(&b); }
  inline void Swap(SimulatorStatus* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimulatorStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SimulatorStatus* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SimulatorStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SimulatorStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SimulatorStatus& from) { SimulatorStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SimulatorStatus* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GUIApp.Comm.SimulatorStatus"; }

 protected:
  explicit SimulatorStatus(::google::protobuf::Arena* arena);
  SimulatorStatus(::google::protobuf::Arena* arena, const SimulatorStatus& from);
  SimulatorStatus(::google::protobuf::Arena* arena, SimulatorStatus&& from) noexcept
      : SimulatorStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpAddressFieldNumber = 2,
    kUptimeSecondsFieldNumber = 1,
    kPortFieldNumber = 3,
  };
  // string ipAddress = 2;
  void clear_ipaddress() ;
  const std::string& ipaddress() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ipaddress(Arg_&& arg, Args_... args);
  std::string* mutable_ipaddress();
  PROTOBUF_NODISCARD std::string* release_ipaddress();
  void set_allocated_ipaddress(std::string* value);

  private:
  const std::string& _internal_ipaddress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ipaddress(
      const std::string& value);
  std::string* _internal_mutable_ipaddress();

  public:
  // int32 uptimeSeconds = 1;
  void clear_uptimeseconds() ;
  ::int32_t uptimeseconds() const;
  void set_uptimeseconds(::int32_t value);

  private:
  ::int32_t _internal_uptimeseconds() const;
  void _internal_set_uptimeseconds(::int32_t value);

  public:
  // int32 port = 3;
  void clear_port() ;
  ::int32_t port() const;
  void set_port(::int32_t value);

  private:
  ::int32_t _internal_port() const;
  void _internal_set_port(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GUIApp.Comm.SimulatorStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      45, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SimulatorStatus& from_msg);
    ::google::protobuf::internal::ArenaStringPtr ipaddress_;
    ::int32_t uptimeseconds_;
    ::int32_t port_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimulatorStatus_2eproto;
};
// -------------------------------------------------------------------

class STAMP_Status final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GUIApp.Comm.STAMP_Status) */ {
 public:
  inline STAMP_Status() : STAMP_Status(nullptr) {}
  ~STAMP_Status() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(STAMP_Status* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(STAMP_Status));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR STAMP_Status(
      ::google::protobuf::internal::ConstantInitialized);

  inline STAMP_Status(const STAMP_Status& from) : STAMP_Status(nullptr, from) {}
  inline STAMP_Status(STAMP_Status&& from) noexcept
      : STAMP_Status(nullptr, std::move(from)) {}
  inline STAMP_Status& operator=(const STAMP_Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline STAMP_Status& operator=(STAMP_Status&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const STAMP_Status& default_instance() {
    return *internal_default_instance();
  }
  static inline const STAMP_Status* internal_default_instance() {
    return reinterpret_cast<const STAMP_Status*>(
        &_STAMP_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(STAMP_Status& a, STAMP_Status& b) { a.Swap(&b); }
  inline void Swap(STAMP_Status* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(STAMP_Status* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  STAMP_Status* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<STAMP_Status>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const STAMP_Status& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const STAMP_Status& from) { STAMP_Status::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(STAMP_Status* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GUIApp.Comm.STAMP_Status"; }

 protected:
  explicit STAMP_Status(::google::protobuf::Arena* arena);
  STAMP_Status(::google::protobuf::Arena* arena, const STAMP_Status& from);
  STAMP_Status(::google::protobuf::Arena* arena, STAMP_Status&& from) noexcept
      : STAMP_Status(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpAddressFieldNumber = 2,
    kUptimeSecondsFieldNumber = 1,
    kPortFieldNumber = 3,
  };
  // string ipAddress = 2;
  void clear_ipaddress() ;
  const std::string& ipaddress() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ipaddress(Arg_&& arg, Args_... args);
  std::string* mutable_ipaddress();
  PROTOBUF_NODISCARD std::string* release_ipaddress();
  void set_allocated_ipaddress(std::string* value);

  private:
  const std::string& _internal_ipaddress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ipaddress(
      const std::string& value);
  std::string* _internal_mutable_ipaddress();

  public:
  // int32 uptimeSeconds = 1;
  void clear_uptimeseconds() ;
  ::int32_t uptimeseconds() const;
  void set_uptimeseconds(::int32_t value);

  private:
  ::int32_t _internal_uptimeseconds() const;
  void _internal_set_uptimeseconds(::int32_t value);

  public:
  // int32 port = 3;
  void clear_port() ;
  ::int32_t port() const;
  void set_port(::int32_t value);

  private:
  ::int32_t _internal_port() const;
  void _internal_set_port(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GUIApp.Comm.STAMP_Status)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      42, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const STAMP_Status& from_msg);
    ::google::protobuf::internal::ArenaStringPtr ipaddress_;
    ::int32_t uptimeseconds_;
    ::int32_t port_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimulatorStatus_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SimulatorStatus

// int32 uptimeSeconds = 1;
inline void SimulatorStatus::clear_uptimeseconds() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uptimeseconds_ = 0;
}
inline ::int32_t SimulatorStatus::uptimeseconds() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.SimulatorStatus.uptimeSeconds)
  return _internal_uptimeseconds();
}
inline void SimulatorStatus::set_uptimeseconds(::int32_t value) {
  _internal_set_uptimeseconds(value);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.SimulatorStatus.uptimeSeconds)
}
inline ::int32_t SimulatorStatus::_internal_uptimeseconds() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uptimeseconds_;
}
inline void SimulatorStatus::_internal_set_uptimeseconds(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uptimeseconds_ = value;
}

// string ipAddress = 2;
inline void SimulatorStatus::clear_ipaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.ClearToEmpty();
}
inline const std::string& SimulatorStatus::ipaddress() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.SimulatorStatus.ipAddress)
  return _internal_ipaddress();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SimulatorStatus::set_ipaddress(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GUIApp.Comm.SimulatorStatus.ipAddress)
}
inline std::string* SimulatorStatus::mutable_ipaddress() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ipaddress();
  // @@protoc_insertion_point(field_mutable:GUIApp.Comm.SimulatorStatus.ipAddress)
  return _s;
}
inline const std::string& SimulatorStatus::_internal_ipaddress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipaddress_.Get();
}
inline void SimulatorStatus::_internal_set_ipaddress(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.Set(value, GetArena());
}
inline std::string* SimulatorStatus::_internal_mutable_ipaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ipaddress_.Mutable( GetArena());
}
inline std::string* SimulatorStatus::release_ipaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GUIApp.Comm.SimulatorStatus.ipAddress)
  return _impl_.ipaddress_.Release();
}
inline void SimulatorStatus::set_allocated_ipaddress(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ipaddress_.IsDefault()) {
    _impl_.ipaddress_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GUIApp.Comm.SimulatorStatus.ipAddress)
}

// int32 port = 3;
inline void SimulatorStatus::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0;
}
inline ::int32_t SimulatorStatus::port() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.SimulatorStatus.port)
  return _internal_port();
}
inline void SimulatorStatus::set_port(::int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.SimulatorStatus.port)
}
inline ::int32_t SimulatorStatus::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void SimulatorStatus::_internal_set_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// -------------------------------------------------------------------

// STAMP_Status

// int32 uptimeSeconds = 1;
inline void STAMP_Status::clear_uptimeseconds() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uptimeseconds_ = 0;
}
inline ::int32_t STAMP_Status::uptimeseconds() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.STAMP_Status.uptimeSeconds)
  return _internal_uptimeseconds();
}
inline void STAMP_Status::set_uptimeseconds(::int32_t value) {
  _internal_set_uptimeseconds(value);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.STAMP_Status.uptimeSeconds)
}
inline ::int32_t STAMP_Status::_internal_uptimeseconds() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uptimeseconds_;
}
inline void STAMP_Status::_internal_set_uptimeseconds(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uptimeseconds_ = value;
}

// string ipAddress = 2;
inline void STAMP_Status::clear_ipaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.ClearToEmpty();
}
inline const std::string& STAMP_Status::ipaddress() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.STAMP_Status.ipAddress)
  return _internal_ipaddress();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void STAMP_Status::set_ipaddress(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GUIApp.Comm.STAMP_Status.ipAddress)
}
inline std::string* STAMP_Status::mutable_ipaddress() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ipaddress();
  // @@protoc_insertion_point(field_mutable:GUIApp.Comm.STAMP_Status.ipAddress)
  return _s;
}
inline const std::string& STAMP_Status::_internal_ipaddress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipaddress_.Get();
}
inline void STAMP_Status::_internal_set_ipaddress(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.Set(value, GetArena());
}
inline std::string* STAMP_Status::_internal_mutable_ipaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ipaddress_.Mutable( GetArena());
}
inline std::string* STAMP_Status::release_ipaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GUIApp.Comm.STAMP_Status.ipAddress)
  return _impl_.ipaddress_.Release();
}
inline void STAMP_Status::set_allocated_ipaddress(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipaddress_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ipaddress_.IsDefault()) {
    _impl_.ipaddress_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GUIApp.Comm.STAMP_Status.ipAddress)
}

// int32 port = 3;
inline void STAMP_Status::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0;
}
inline ::int32_t STAMP_Status::port() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.STAMP_Status.port)
  return _internal_port();
}
inline void STAMP_Status::set_port(::int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.STAMP_Status.port)
}
inline ::int32_t STAMP_Status::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void STAMP_Status::_internal_set_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// -------------------------------------------------------------------

// SubsystemStatus

// .GUIApp.Comm.SystemStatus status = 1;
inline void SubsystemStatus::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
}
inline ::GUIApp::Comm::SystemStatus SubsystemStatus::status() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.SubsystemStatus.status)
  return _internal_status();
}
inline void SubsystemStatus::set_status(::GUIApp::Comm::SystemStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.SubsystemStatus.status)
}
inline ::GUIApp::Comm::SystemStatus SubsystemStatus::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GUIApp::Comm::SystemStatus>(_impl_.status_);
}
inline void SubsystemStatus::_internal_set_status(::GUIApp::Comm::SystemStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GUIApp::Comm::SystemStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::GUIApp::Comm::SystemStatus>() {
  return ::GUIApp::Comm::SystemStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SimulatorStatus_2eproto_2epb_2eh
