// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: STAMP_Control.proto
// Protobuf C++ Version: 6.33.1

#ifndef STAMP_5fControl_2eproto_2epb_2eh
#define STAMP_5fControl_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_STAMP_5fControl_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_STAMP_5fControl_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_STAMP_5fControl_2eproto;
}  // extern "C"
namespace GUIApp {
namespace Comm {
enum Command : int;
extern const uint32_t Command_internal_data_[];
class STAMP_Control;
struct STAMP_ControlDefaultTypeInternal;
extern STAMP_ControlDefaultTypeInternal _STAMP_Control_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull STAMP_Control_class_data_;
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::GUIApp::Comm::Command_internal_data_>
    internal::EnumTraitsImpl::value<::GUIApp::Comm::Command>;
}  // namespace protobuf
}  // namespace google

namespace GUIApp {
namespace Comm {
enum Command : int {
  Start = 0,
  Stop = 1,
  Command_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Command_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Command_internal_data_[];
inline constexpr Command Command_MIN =
    static_cast<Command>(0);
inline constexpr Command Command_MAX =
    static_cast<Command>(1);
inline bool Command_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int Command_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Command_descriptor();
template <typename T>
const ::std::string& Command_Name(T value) {
  static_assert(::std::is_same<T, Command>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Command_Name().");
  return Command_Name(static_cast<Command>(value));
}
template <>
inline const ::std::string& Command_Name(Command value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Command_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool Command_Parse(
    ::absl::string_view name, Command* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Command>(Command_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class STAMP_Control final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GUIApp.Comm.STAMP_Control) */ {
 public:
  inline STAMP_Control() : STAMP_Control(nullptr) {}
  ~STAMP_Control() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(STAMP_Control* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(STAMP_Control));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR STAMP_Control(::google::protobuf::internal::ConstantInitialized);

  inline STAMP_Control(const STAMP_Control& from) : STAMP_Control(nullptr, from) {}
  inline STAMP_Control(STAMP_Control&& from) noexcept
      : STAMP_Control(nullptr, ::std::move(from)) {}
  inline STAMP_Control& operator=(const STAMP_Control& from) {
    CopyFrom(from);
    return *this;
  }
  inline STAMP_Control& operator=(STAMP_Control&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const STAMP_Control& default_instance() {
    return *reinterpret_cast<const STAMP_Control*>(
        &_STAMP_Control_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(STAMP_Control& a, STAMP_Control& b) { a.Swap(&b); }
  inline void Swap(STAMP_Control* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(STAMP_Control* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  STAMP_Control* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<STAMP_Control>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const STAMP_Control& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const STAMP_Control& from) { STAMP_Control::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(STAMP_Control* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GUIApp.Comm.STAMP_Control"; }

  explicit STAMP_Control(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  STAMP_Control(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const STAMP_Control& from);
  STAMP_Control(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, STAMP_Control&& from) noexcept
      : STAMP_Control(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSTAMPCommandFieldNumber = 1,
  };
  // .GUIApp.Comm.Command STAMP_Command = 1;
  void clear_stamp_command() ;
  ::GUIApp::Comm::Command stamp_command() const;
  void set_stamp_command(::GUIApp::Comm::Command value);

  private:
  ::GUIApp::Comm::Command _internal_stamp_command() const;
  void _internal_set_stamp_command(::GUIApp::Comm::Command value);

  public:
  // @@protoc_insertion_point(class_scope:GUIApp.Comm.STAMP_Control)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const STAMP_Control& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int stamp_command_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_STAMP_5fControl_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull STAMP_Control_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// STAMP_Control

// .GUIApp.Comm.Command STAMP_Command = 1;
inline void STAMP_Control::clear_stamp_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamp_command_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::GUIApp::Comm::Command STAMP_Control::stamp_command() const {
  // @@protoc_insertion_point(field_get:GUIApp.Comm.STAMP_Control.STAMP_Command)
  return _internal_stamp_command();
}
inline void STAMP_Control::set_stamp_command(::GUIApp::Comm::Command value) {
  _internal_set_stamp_command(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:GUIApp.Comm.STAMP_Control.STAMP_Command)
}
inline ::GUIApp::Comm::Command STAMP_Control::_internal_stamp_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GUIApp::Comm::Command>(_impl_.stamp_command_);
}
inline void STAMP_Control::_internal_set_stamp_command(::GUIApp::Comm::Command value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stamp_command_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GUIApp::Comm::Command> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GUIApp::Comm::Command>() {
  return ::GUIApp::Comm::Command_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // STAMP_5fControl_2eproto_2epb_2eh
