// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: STAMP_Control.proto
// Protobuf C++ Version: 6.33.1

#include "STAMP_Control.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GUIApp {
namespace Comm {

inline constexpr STAMP_Control::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        stamp_command_{static_cast< ::GUIApp::Comm::Command >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR STAMP_Control::STAMP_Control(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(STAMP_Control_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct STAMP_ControlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR STAMP_ControlDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~STAMP_ControlDefaultTypeInternal() {}
  union {
    STAMP_Control _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 STAMP_ControlDefaultTypeInternal _STAMP_Control_default_instance_;
}  // namespace Comm
}  // namespace GUIApp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_STAMP_5fControl_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_STAMP_5fControl_2eproto = nullptr;
const ::uint32_t
    TableStruct_STAMP_5fControl_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::STAMP_Control, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GUIApp::Comm::STAMP_Control, _impl_.stamp_command_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::GUIApp::Comm::STAMP_Control)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::GUIApp::Comm::_STAMP_Control_default_instance_._instance,
};
const char descriptor_table_protodef_STAMP_5fControl_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023STAMP_Control.proto\022\013GUIApp.Comm\"<\n\rST"
    "AMP_Control\022+\n\rSTAMP_Command\030\001 \001(\0162\024.GUI"
    "App.Comm.Command*\036\n\007Command\022\t\n\005Start\020\000\022\010"
    "\n\004Stop\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_STAMP_5fControl_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_STAMP_5fControl_2eproto = {
    false,
    false,
    136,
    descriptor_table_protodef_STAMP_5fControl_2eproto,
    "STAMP_Control.proto",
    &descriptor_table_STAMP_5fControl_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_STAMP_5fControl_2eproto::offsets,
    file_level_enum_descriptors_STAMP_5fControl_2eproto,
    file_level_service_descriptors_STAMP_5fControl_2eproto,
};
namespace GUIApp {
namespace Comm {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Command_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_STAMP_5fControl_2eproto);
  return file_level_enum_descriptors_STAMP_5fControl_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Command_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class STAMP_Control::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<STAMP_Control>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(STAMP_Control, _impl_._has_bits_);
};

STAMP_Control::STAMP_Control(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, STAMP_Control_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GUIApp.Comm.STAMP_Control)
}
STAMP_Control::STAMP_Control(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const STAMP_Control& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, STAMP_Control_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE STAMP_Control::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void STAMP_Control::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.stamp_command_ = {};
}
STAMP_Control::~STAMP_Control() {
  // @@protoc_insertion_point(destructor:GUIApp.Comm.STAMP_Control)
  SharedDtor(*this);
}
inline void STAMP_Control::SharedDtor(MessageLite& self) {
  STAMP_Control& this_ = static_cast<STAMP_Control&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL STAMP_Control::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) STAMP_Control(arena);
}
constexpr auto STAMP_Control::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(STAMP_Control),
                                            alignof(STAMP_Control));
}
constexpr auto STAMP_Control::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_STAMP_Control_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &STAMP_Control::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<STAMP_Control>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &STAMP_Control::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<STAMP_Control>(), &STAMP_Control::ByteSizeLong,
              &STAMP_Control::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(STAMP_Control, _impl_._cached_size_),
          false,
      },
      &STAMP_Control::kDescriptorMethods,
      &descriptor_table_STAMP_5fControl_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull STAMP_Control_class_data_ =
        STAMP_Control::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
STAMP_Control::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&STAMP_Control_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(STAMP_Control_class_data_.tc_table);
  return STAMP_Control_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
STAMP_Control::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(STAMP_Control, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    STAMP_Control_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GUIApp::Comm::STAMP_Control>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .GUIApp.Comm.Command STAMP_Command = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(STAMP_Control, _impl_.stamp_command_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(STAMP_Control, _impl_.stamp_command_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GUIApp.Comm.Command STAMP_Command = 1;
    {PROTOBUF_FIELD_OFFSET(STAMP_Control, _impl_.stamp_command_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void STAMP_Control::Clear() {
// @@protoc_insertion_point(message_clear_start:GUIApp.Comm.STAMP_Control)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stamp_command_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL STAMP_Control::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const STAMP_Control& this_ = static_cast<const STAMP_Control&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL STAMP_Control::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const STAMP_Control& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GUIApp.Comm.STAMP_Control)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .GUIApp.Comm.Command STAMP_Command = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_stamp_command() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_stamp_command(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GUIApp.Comm.STAMP_Control)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t STAMP_Control::ByteSizeLong(const MessageLite& base) {
  const STAMP_Control& this_ = static_cast<const STAMP_Control&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t STAMP_Control::ByteSizeLong() const {
  const STAMP_Control& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GUIApp.Comm.STAMP_Control)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .GUIApp.Comm.Command STAMP_Command = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_stamp_command() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_stamp_command());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void STAMP_Control::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<STAMP_Control*>(&to_msg);
  auto& from = static_cast<const STAMP_Control&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GUIApp.Comm.STAMP_Control)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_stamp_command() != 0) {
      _this->_impl_.stamp_command_ = from._impl_.stamp_command_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void STAMP_Control::CopyFrom(const STAMP_Control& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GUIApp.Comm.STAMP_Control)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void STAMP_Control::InternalSwap(STAMP_Control* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.stamp_command_, other->_impl_.stamp_command_);
}

::google::protobuf::Metadata STAMP_Control::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Comm
}  // namespace GUIApp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_STAMP_5fControl_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
