// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigureBitResults.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GUIApp.Comm {

  /// <summary>Holder for reflection information generated from ConfigureBitResults.proto</summary>
  public static partial class ConfigureBitResultsReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigureBitResults.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigureBitResultsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDb25maWd1cmVCaXRSZXN1bHRzLnByb3RvEgtHVUlBcHAuQ29tbSJrChND",
            "b25maWd1cmVCaXRSZXN1bHRzEjIKC0JpdFJlc3BvbnNlGAEgASgOMh0uR1VJ",
            "QXBwLkNvbW0uQklUX1Jlc3BvbnNlVHlwZRIgChhEdXJhdGlvbklmU2V0VG9G",
            "YWlsX21zZWMYAiABKAUqQAoQQklUX1Jlc3BvbnNlVHlwZRIVChFCSVRfUkVT",
            "UE9OU0VfUEFTUxAAEhUKEUJJVF9SRVNQT05TRV9GQUlMEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GUIApp.Comm.BIT_ResponseType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GUIApp.Comm.ConfigureBitResults), global::GUIApp.Comm.ConfigureBitResults.Parser, new[]{ "BitResponse", "DurationIfSetToFailMsec" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum BIT_ResponseType {
    [pbr::OriginalName("BIT_RESPONSE_PASS")] BitResponsePass = 0,
    [pbr::OriginalName("BIT_RESPONSE_FAIL")] BitResponseFail = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConfigureBitResults : pb::IMessage<ConfigureBitResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigureBitResults> _parser = new pb::MessageParser<ConfigureBitResults>(() => new ConfigureBitResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConfigureBitResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GUIApp.Comm.ConfigureBitResultsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigureBitResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigureBitResults(ConfigureBitResults other) : this() {
      bitResponse_ = other.bitResponse_;
      durationIfSetToFailMsec_ = other.durationIfSetToFailMsec_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigureBitResults Clone() {
      return new ConfigureBitResults(this);
    }

    /// <summary>Field number for the "BitResponse" field.</summary>
    public const int BitResponseFieldNumber = 1;
    private global::GUIApp.Comm.BIT_ResponseType bitResponse_ = global::GUIApp.Comm.BIT_ResponseType.BitResponsePass;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.BIT_ResponseType BitResponse {
      get { return bitResponse_; }
      set {
        bitResponse_ = value;
      }
    }

    /// <summary>Field number for the "DurationIfSetToFail_msec" field.</summary>
    public const int DurationIfSetToFailMsecFieldNumber = 2;
    private int durationIfSetToFailMsec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DurationIfSetToFailMsec {
      get { return durationIfSetToFailMsec_; }
      set {
        durationIfSetToFailMsec_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConfigureBitResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConfigureBitResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BitResponse != other.BitResponse) return false;
      if (DurationIfSetToFailMsec != other.DurationIfSetToFailMsec) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) hash ^= BitResponse.GetHashCode();
      if (DurationIfSetToFailMsec != 0) hash ^= DurationIfSetToFailMsec.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BitResponse);
      }
      if (DurationIfSetToFailMsec != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DurationIfSetToFailMsec);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BitResponse);
      }
      if (DurationIfSetToFailMsec != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DurationIfSetToFailMsec);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BitResponse);
      }
      if (DurationIfSetToFailMsec != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DurationIfSetToFailMsec);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConfigureBitResults other) {
      if (other == null) {
        return;
      }
      if (other.BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        BitResponse = other.BitResponse;
      }
      if (other.DurationIfSetToFailMsec != 0) {
        DurationIfSetToFailMsec = other.DurationIfSetToFailMsec;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BitResponse = (global::GUIApp.Comm.BIT_ResponseType) input.ReadEnum();
            break;
          }
          case 16: {
            DurationIfSetToFailMsec = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BitResponse = (global::GUIApp.Comm.BIT_ResponseType) input.ReadEnum();
            break;
          }
          case 16: {
            DurationIfSetToFailMsec = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
