# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ConfigureBitResults.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'ConfigureBitResults.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x43onfigureBitResults.proto\x12\x0bGUIApp.Comm\"\xeb\x03\n\x13\x43onfigureBitResults\x12\x32\n\x0b\x42itResponse\x18\x01 \x01(\x0e\x32\x1d.GUIApp.Comm.BIT_ResponseType\x12\x1f\n\x17\x44urationOfResponse_msec\x18\x02 \x01(\x05\x12\x35\n\x0fSensor_1_Status\x18\x03 \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus\x12\x35\n\x0fSensor_2_Status\x18\x04 \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus\x12\x35\n\x0fSensor_3_Status\x18\x05 \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus\x12\x35\n\x0fSensor_4_Status\x18\x06 \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus\x12\x35\n\x0fSensor_5_Status\x18\x07 \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus\x12\x35\n\x0fSensor_6_Status\x18\x08 \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus\x12\x35\n\x0fHeimdall_Status\x18\t \x01(\x0e\x32\x1c.GUIApp.Comm.ComponentStatus*@\n\x10\x42IT_ResponseType\x12\x15\n\x11\x42IT_RESPONSE_PASS\x10\x00\x12\x15\n\x11\x42IT_RESPONSE_FAIL\x10\x01*i\n\x0f\x43omponentStatus\x12\x07\n\x03OFF\x10\x00\x12\x19\n\x15\x43omponentInitializing\x10\x01\x12\x18\n\x14\x43omponentOperational\x10\x02\x12\x0c\n\x08\x44\x65graded\x10\x03\x12\n\n\x06\x46\x61iled\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConfigureBitResults_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIT_RESPONSETYPE']._serialized_start=536
  _globals['_BIT_RESPONSETYPE']._serialized_end=600
  _globals['_COMPONENTSTATUS']._serialized_start=602
  _globals['_COMPONENTSTATUS']._serialized_end=707
  _globals['_CONFIGUREBITRESULTS']._serialized_start=43
  _globals['_CONFIGUREBITRESULTS']._serialized_end=534
# @@protoc_insertion_point(module_scope)
