# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Configure_STAMP_Status.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'Configure_STAMP_Status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43onfigure_STAMP_Status.proto\x12\x0bGUIApp.Comm\"C\n\x16\x43onfigure_STAMP_Status\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.GUIApp.Comm.SystemStatus*e\n\x0cSystemStatus\x12\x17\n\x13Status_Initializing\x10\x00\x12\x11\n\rStatus_Normal\x10\x01\x12\x13\n\x0fStatus_Degraded\x10\x02\x12\x14\n\x10Status_Inoprable\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Configure_STAMP_Status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMSTATUS']._serialized_start=114
  _globals['_SYSTEMSTATUS']._serialized_end=215
  _globals['_CONFIGURE_STAMP_STATUS']._serialized_start=45
  _globals['_CONFIGURE_STAMP_STATUS']._serialized_end=112
# @@protoc_insertion_point(module_scope)
