# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: STAMP_Control.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'STAMP_Control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13STAMP_Control.proto\x12\x0bGUIApp.Comm\"<\n\rSTAMP_Control\x12+\n\rSTAMP_Command\x18\x01 \x01(\x0e\x32\x14.GUIApp.Comm.Command*\x1e\n\x07\x43ommand\x12\t\n\x05Start\x10\x00\x12\x08\n\x04Stop\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'STAMP_Control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=98
  _globals['_COMMAND']._serialized_end=128
  _globals['_STAMP_CONTROL']._serialized_start=36
  _globals['_STAMP_CONTROL']._serialized_end=96
# @@protoc_insertion_point(module_scope)
