// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigureBitResults.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GUIApp.Comm {

  /// <summary>Holder for reflection information generated from ConfigureBitResults.proto</summary>
  public static partial class ConfigureBitResultsReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigureBitResults.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigureBitResultsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDb25maWd1cmVCaXRSZXN1bHRzLnByb3RvEgtHVUlBcHAuQ29tbSLrAwoT",
            "Q29uZmlndXJlQml0UmVzdWx0cxIyCgtCaXRSZXNwb25zZRgBIAEoDjIdLkdV",
            "SUFwcC5Db21tLkJJVF9SZXNwb25zZVR5cGUSHwoXRHVyYXRpb25PZlJlc3Bv",
            "bnNlX21zZWMYAiABKAUSNQoPU2Vuc29yXzFfU3RhdHVzGAMgASgOMhwuR1VJ",
            "QXBwLkNvbW0uQ29tcG9uZW50U3RhdHVzEjUKD1NlbnNvcl8yX1N0YXR1cxgE",
            "IAEoDjIcLkdVSUFwcC5Db21tLkNvbXBvbmVudFN0YXR1cxI1Cg9TZW5zb3Jf",
            "M19TdGF0dXMYBSABKA4yHC5HVUlBcHAuQ29tbS5Db21wb25lbnRTdGF0dXMS",
            "NQoPU2Vuc29yXzRfU3RhdHVzGAYgASgOMhwuR1VJQXBwLkNvbW0uQ29tcG9u",
            "ZW50U3RhdHVzEjUKD1NlbnNvcl81X1N0YXR1cxgHIAEoDjIcLkdVSUFwcC5D",
            "b21tLkNvbXBvbmVudFN0YXR1cxI1Cg9TZW5zb3JfNl9TdGF0dXMYCCABKA4y",
            "HC5HVUlBcHAuQ29tbS5Db21wb25lbnRTdGF0dXMSNQoPSGVpbWRhbGxfU3Rh",
            "dHVzGAkgASgOMhwuR1VJQXBwLkNvbW0uQ29tcG9uZW50U3RhdHVzKkAKEEJJ",
            "VF9SZXNwb25zZVR5cGUSFQoRQklUX1JFU1BPTlNFX1BBU1MQABIVChFCSVRf",
            "UkVTUE9OU0VfRkFJTBABKmkKD0NvbXBvbmVudFN0YXR1cxIHCgNPRkYQABIZ",
            "ChVDb21wb25lbnRJbml0aWFsaXppbmcQARIYChRDb21wb25lbnRPcGVyYXRp",
            "b25hbBACEgwKCERlZ3JhZGVkEAMSCgoGRmFpbGVkEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GUIApp.Comm.BIT_ResponseType), typeof(global::GUIApp.Comm.ComponentStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GUIApp.Comm.ConfigureBitResults), global::GUIApp.Comm.ConfigureBitResults.Parser, new[]{ "BitResponse", "DurationOfResponseMsec", "Sensor1Status", "Sensor2Status", "Sensor3Status", "Sensor4Status", "Sensor5Status", "Sensor6Status", "HeimdallStatus" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum BIT_ResponseType {
    [pbr::OriginalName("BIT_RESPONSE_PASS")] BitResponsePass = 0,
    [pbr::OriginalName("BIT_RESPONSE_FAIL")] BitResponseFail = 1,
  }

  public enum ComponentStatus {
    [pbr::OriginalName("OFF")] Off = 0,
    [pbr::OriginalName("ComponentInitializing")] ComponentInitializing = 1,
    [pbr::OriginalName("ComponentOperational")] ComponentOperational = 2,
    [pbr::OriginalName("Degraded")] Degraded = 3,
    [pbr::OriginalName("Failed")] Failed = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConfigureBitResults : pb::IMessage<ConfigureBitResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigureBitResults> _parser = new pb::MessageParser<ConfigureBitResults>(() => new ConfigureBitResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConfigureBitResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GUIApp.Comm.ConfigureBitResultsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigureBitResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigureBitResults(ConfigureBitResults other) : this() {
      bitResponse_ = other.bitResponse_;
      durationOfResponseMsec_ = other.durationOfResponseMsec_;
      sensor1Status_ = other.sensor1Status_;
      sensor2Status_ = other.sensor2Status_;
      sensor3Status_ = other.sensor3Status_;
      sensor4Status_ = other.sensor4Status_;
      sensor5Status_ = other.sensor5Status_;
      sensor6Status_ = other.sensor6Status_;
      heimdallStatus_ = other.heimdallStatus_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfigureBitResults Clone() {
      return new ConfigureBitResults(this);
    }

    /// <summary>Field number for the "BitResponse" field.</summary>
    public const int BitResponseFieldNumber = 1;
    private global::GUIApp.Comm.BIT_ResponseType bitResponse_ = global::GUIApp.Comm.BIT_ResponseType.BitResponsePass;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.BIT_ResponseType BitResponse {
      get { return bitResponse_; }
      set {
        bitResponse_ = value;
      }
    }

    /// <summary>Field number for the "DurationOfResponse_msec" field.</summary>
    public const int DurationOfResponseMsecFieldNumber = 2;
    private int durationOfResponseMsec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DurationOfResponseMsec {
      get { return durationOfResponseMsec_; }
      set {
        durationOfResponseMsec_ = value;
      }
    }

    /// <summary>Field number for the "Sensor_1_Status" field.</summary>
    public const int Sensor1StatusFieldNumber = 3;
    private global::GUIApp.Comm.ComponentStatus sensor1Status_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus Sensor1Status {
      get { return sensor1Status_; }
      set {
        sensor1Status_ = value;
      }
    }

    /// <summary>Field number for the "Sensor_2_Status" field.</summary>
    public const int Sensor2StatusFieldNumber = 4;
    private global::GUIApp.Comm.ComponentStatus sensor2Status_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus Sensor2Status {
      get { return sensor2Status_; }
      set {
        sensor2Status_ = value;
      }
    }

    /// <summary>Field number for the "Sensor_3_Status" field.</summary>
    public const int Sensor3StatusFieldNumber = 5;
    private global::GUIApp.Comm.ComponentStatus sensor3Status_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus Sensor3Status {
      get { return sensor3Status_; }
      set {
        sensor3Status_ = value;
      }
    }

    /// <summary>Field number for the "Sensor_4_Status" field.</summary>
    public const int Sensor4StatusFieldNumber = 6;
    private global::GUIApp.Comm.ComponentStatus sensor4Status_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus Sensor4Status {
      get { return sensor4Status_; }
      set {
        sensor4Status_ = value;
      }
    }

    /// <summary>Field number for the "Sensor_5_Status" field.</summary>
    public const int Sensor5StatusFieldNumber = 7;
    private global::GUIApp.Comm.ComponentStatus sensor5Status_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus Sensor5Status {
      get { return sensor5Status_; }
      set {
        sensor5Status_ = value;
      }
    }

    /// <summary>Field number for the "Sensor_6_Status" field.</summary>
    public const int Sensor6StatusFieldNumber = 8;
    private global::GUIApp.Comm.ComponentStatus sensor6Status_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus Sensor6Status {
      get { return sensor6Status_; }
      set {
        sensor6Status_ = value;
      }
    }

    /// <summary>Field number for the "Heimdall_Status" field.</summary>
    public const int HeimdallStatusFieldNumber = 9;
    private global::GUIApp.Comm.ComponentStatus heimdallStatus_ = global::GUIApp.Comm.ComponentStatus.Off;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIApp.Comm.ComponentStatus HeimdallStatus {
      get { return heimdallStatus_; }
      set {
        heimdallStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConfigureBitResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConfigureBitResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BitResponse != other.BitResponse) return false;
      if (DurationOfResponseMsec != other.DurationOfResponseMsec) return false;
      if (Sensor1Status != other.Sensor1Status) return false;
      if (Sensor2Status != other.Sensor2Status) return false;
      if (Sensor3Status != other.Sensor3Status) return false;
      if (Sensor4Status != other.Sensor4Status) return false;
      if (Sensor5Status != other.Sensor5Status) return false;
      if (Sensor6Status != other.Sensor6Status) return false;
      if (HeimdallStatus != other.HeimdallStatus) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) hash ^= BitResponse.GetHashCode();
      if (DurationOfResponseMsec != 0) hash ^= DurationOfResponseMsec.GetHashCode();
      if (Sensor1Status != global::GUIApp.Comm.ComponentStatus.Off) hash ^= Sensor1Status.GetHashCode();
      if (Sensor2Status != global::GUIApp.Comm.ComponentStatus.Off) hash ^= Sensor2Status.GetHashCode();
      if (Sensor3Status != global::GUIApp.Comm.ComponentStatus.Off) hash ^= Sensor3Status.GetHashCode();
      if (Sensor4Status != global::GUIApp.Comm.ComponentStatus.Off) hash ^= Sensor4Status.GetHashCode();
      if (Sensor5Status != global::GUIApp.Comm.ComponentStatus.Off) hash ^= Sensor5Status.GetHashCode();
      if (Sensor6Status != global::GUIApp.Comm.ComponentStatus.Off) hash ^= Sensor6Status.GetHashCode();
      if (HeimdallStatus != global::GUIApp.Comm.ComponentStatus.Off) hash ^= HeimdallStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BitResponse);
      }
      if (DurationOfResponseMsec != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DurationOfResponseMsec);
      }
      if (Sensor1Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Sensor1Status);
      }
      if (Sensor2Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Sensor2Status);
      }
      if (Sensor3Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Sensor3Status);
      }
      if (Sensor4Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Sensor4Status);
      }
      if (Sensor5Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Sensor5Status);
      }
      if (Sensor6Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Sensor6Status);
      }
      if (HeimdallStatus != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(72);
        output.WriteEnum((int) HeimdallStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BitResponse);
      }
      if (DurationOfResponseMsec != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DurationOfResponseMsec);
      }
      if (Sensor1Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Sensor1Status);
      }
      if (Sensor2Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Sensor2Status);
      }
      if (Sensor3Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Sensor3Status);
      }
      if (Sensor4Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Sensor4Status);
      }
      if (Sensor5Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Sensor5Status);
      }
      if (Sensor6Status != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Sensor6Status);
      }
      if (HeimdallStatus != global::GUIApp.Comm.ComponentStatus.Off) {
        output.WriteRawTag(72);
        output.WriteEnum((int) HeimdallStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BitResponse);
      }
      if (DurationOfResponseMsec != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DurationOfResponseMsec);
      }
      if (Sensor1Status != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sensor1Status);
      }
      if (Sensor2Status != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sensor2Status);
      }
      if (Sensor3Status != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sensor3Status);
      }
      if (Sensor4Status != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sensor4Status);
      }
      if (Sensor5Status != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sensor5Status);
      }
      if (Sensor6Status != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sensor6Status);
      }
      if (HeimdallStatus != global::GUIApp.Comm.ComponentStatus.Off) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) HeimdallStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConfigureBitResults other) {
      if (other == null) {
        return;
      }
      if (other.BitResponse != global::GUIApp.Comm.BIT_ResponseType.BitResponsePass) {
        BitResponse = other.BitResponse;
      }
      if (other.DurationOfResponseMsec != 0) {
        DurationOfResponseMsec = other.DurationOfResponseMsec;
      }
      if (other.Sensor1Status != global::GUIApp.Comm.ComponentStatus.Off) {
        Sensor1Status = other.Sensor1Status;
      }
      if (other.Sensor2Status != global::GUIApp.Comm.ComponentStatus.Off) {
        Sensor2Status = other.Sensor2Status;
      }
      if (other.Sensor3Status != global::GUIApp.Comm.ComponentStatus.Off) {
        Sensor3Status = other.Sensor3Status;
      }
      if (other.Sensor4Status != global::GUIApp.Comm.ComponentStatus.Off) {
        Sensor4Status = other.Sensor4Status;
      }
      if (other.Sensor5Status != global::GUIApp.Comm.ComponentStatus.Off) {
        Sensor5Status = other.Sensor5Status;
      }
      if (other.Sensor6Status != global::GUIApp.Comm.ComponentStatus.Off) {
        Sensor6Status = other.Sensor6Status;
      }
      if (other.HeimdallStatus != global::GUIApp.Comm.ComponentStatus.Off) {
        HeimdallStatus = other.HeimdallStatus;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BitResponse = (global::GUIApp.Comm.BIT_ResponseType) input.ReadEnum();
            break;
          }
          case 16: {
            DurationOfResponseMsec = input.ReadInt32();
            break;
          }
          case 24: {
            Sensor1Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 32: {
            Sensor2Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 40: {
            Sensor3Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 48: {
            Sensor4Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 56: {
            Sensor5Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 64: {
            Sensor6Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 72: {
            HeimdallStatus = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BitResponse = (global::GUIApp.Comm.BIT_ResponseType) input.ReadEnum();
            break;
          }
          case 16: {
            DurationOfResponseMsec = input.ReadInt32();
            break;
          }
          case 24: {
            Sensor1Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 32: {
            Sensor2Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 40: {
            Sensor3Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 48: {
            Sensor4Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 56: {
            Sensor5Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 64: {
            Sensor6Status = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
          case 72: {
            HeimdallStatus = (global::GUIApp.Comm.ComponentStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
